### PR TITLE
feat: bump dependencies

### PR DESCRIPTION
**Pull request by odsod**

### CODE REVIEW

**Comment by alethenorio** [comment]
@odsod have we tested this? Eslint v9 is not supported by typescript-eslint v7 so this might not work downstream 

https://github.com/typescript-eslint/typescript-eslint/issues/8211#issue-2069340518

**Comment by odsod** [comment]
@alethenorio no not beyond this repo - what would be a typical process for testing these bumps? where would the issue be detected if not here?

**Comment by alethenorio** [comment]
I think this is imported by our frontend repos so you could try to change their dependency. Been a while since I looked at this but I think you can define a dependency in package.json to be another folder locally

**Comment by alethenorio** [comment]
But yes if this is indeed an issue we should ideally be detecting it here

**Comment by odsod** [comment]
@alethenorio I see! Maybe we should look into combining some of these small libs (eslint, tsconfig, etc), since they have cross-dependnecies.

**Pull request closed without merging**
